# Generated by Django 5.2.15 on 2026-06-24 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='城市名称')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='城市编码')),
                ('region', models.CharField(blank=True, max_length=64, null=True, verbose_name='所属地区')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=64, verbose_name='员工姓名')),
                ('job_no', models.CharField(max_length=64, unique=True, verbose_name='工号')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='ComputerRoom',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=128, verbose_name='机房名称')),
                ('code', models.CharField(max_length=64, verbose_name='机房编码')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='机房地址')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '停用'), ('maintenance', '维护中')], default='enabled', max_length=32, verbose_name='机房状态')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='computer_rooms', to='hosts.city', verbose_name='所属城市')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_rooms', to='hosts.employee', verbose_name='机房负责人')),
            ],
            options={
                'verbose_name': '机房',
                'verbose_name_plural': '机房',
                'db_table': 'computer_room',
                'unique_together': {('city', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=128, verbose_name='组织名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='组织编码')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='hosts.organization', verbose_name='上级组织')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '组织',
                'verbose_name_plural': '组织',
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('hostname', models.CharField(max_length=128, unique=True, verbose_name='主机名')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='主机IP')),
                ('manage_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='管理IP')),
                ('host_type', models.CharField(choices=[('physical', '物理机'), ('virtual', '虚拟机'), ('cloud', '云主机')], default='physical', max_length=32, verbose_name='主机类型')),
                ('environment', models.CharField(choices=[('dev', '开发环境'), ('test', '测试环境'), ('prod', '生产环境')], default='prod', max_length=32, verbose_name='运行环境')),
                ('os_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='操作系统')),
                ('cpu_core', models.PositiveIntegerField(default=0, verbose_name='CPU核心数')),
                ('memory_gb', models.PositiveIntegerField(default=0, verbose_name='内存GB')),
                ('disk_gb', models.PositiveIntegerField(default=0, verbose_name='磁盘GB')),
                ('status', models.CharField(choices=[('running', '运行中'), ('stopped', '已停止'), ('maintenance', '维护中'), ('offline', '已下线')], default='running', max_length=32, verbose_name='主机状态')),
                ('last_check_time', models.DateTimeField(blank=True, null=True, verbose_name='上次检查时间')),
                ('last_check_result', models.BooleanField(blank=True, null=True, verbose_name='上次检查结果')),
                ('computer_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosts', to='hosts.computerroom', verbose_name='所属机房')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_hosts', to='hosts.employee', verbose_name='负责人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosts', to='hosts.organization', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '主机',
                'verbose_name_plural': '主机',
                'db_table': 'host',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='hosts.organization', verbose_name='所属组织'),
        ),
        migrations.CreateModel(
            name='HostDailyStatistic',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('statistic_date', models.DateField(verbose_name='统计日期')),
                ('host_count', models.PositiveIntegerField(default=0, verbose_name='主机数量')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='host_statistics', to='hosts.city', verbose_name='城市')),
                ('computer_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='host_statistics', to='hosts.computerroom', verbose_name='机房')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '每日主机统计',
                'verbose_name_plural': '每日主机统计',
                'db_table': 'host_daily_statistic',
                'constraints': [models.UniqueConstraint(fields=('statistic_date', 'city', 'computer_room'), name='uniq_host_daily_statistic_date_city_room')],
            },
        ),
    ]
