# Generated by Django 5.2.15 on 2026-06-25 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostConnectivityLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('check_time', models.DateTimeField(verbose_name='探测时间')),
                ('reachable', models.BooleanField(verbose_name='是否可达')),
                ('check_type', models.CharField(choices=[('manual', '手动探测'), ('batch', '批量探测'), ('scheduled', '定时探测')], default='manual', max_length=32, verbose_name='探测类型')),
                ('target_ip', models.GenericIPAddressField(verbose_name='探测IP')),
                ('command', models.CharField(max_length=255, verbose_name='执行命令')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='耗时毫秒')),
                ('return_code', models.IntegerField(blank=True, null=True, verbose_name='返回码')),
                ('output', models.TextField(blank=True, null=True, verbose_name='输出内容')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connectivity_logs', to='hosts.host', verbose_name='主机')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '主机连通性日志',
                'verbose_name_plural': '主机连通性日志',
                'db_table': 'host_connectivity_log',
                'ordering': ('-check_time', '-id'),
            },
        ),
    ]
