# Generated by Django 5.2.15 on 2026-06-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_hostconnectivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostdailystatistic',
            name='reachable_count',
            field=models.PositiveIntegerField(default=0, verbose_name='可达数量'),
        ),
        migrations.AddField(
            model_name='hostdailystatistic',
            name='unreachable_count',
            field=models.PositiveIntegerField(default=0, verbose_name='不可达数量'),
        ),
    ]
